"""
Application defaults. All values can be overridden via .env
"""

DEFAULTS = {
    "CHUNK_DURATION_MINUTES": 30,
    "NDI_DISCOVERY_TIMEOUT_MS": 5000,
    "NDI_RESCAN_INTERVAL_SECONDS": 30,
    "RETENTION_RAW_DAYS": 7,
    "RETENTION_COMPRESSED_DAYS": 365,
    "COMPRESSION_SCHEDULE_HOUR": 2,
    "LOCAL_BUFFER_MAX_GB": 50,
    "S3_PREFIX": "recordings",
    "CPU_POLL_INTERVAL_SECONDS": 2,
    "SYSTEM_SNAPSHOT_RETENTION_HOURS": 24,
}
